package BMIprojek;
import javax.swing.JTabbedPane;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JFrame;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;

/**
 *
 * @author asus
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pasienTambahButton2 = new javax.swing.JButton();
        pasienHapusButton2 = new javax.swing.JButton();
        pasienUbahButton2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        pasienDataTabel2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        mainPanel = new javax.swing.JPanel();
        splitPanel = new javax.swing.JSplitPane();
        headerPanel = new javax.swing.JPanel();
        pencarianButton = new javax.swing.JButton();
        pencarianText = new javax.swing.JTextField();
        namaAkunLabel = new javax.swing.JLabel();
        pencarianLabel = new javax.swing.JLabel();
        subPanel = new javax.swing.JTabbedPane();
        kaderPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kaderDataTabel = new javax.swing.JTable();
        kaderTambahButton = new javax.swing.JButton();
        kaderHapusButton = new javax.swing.JButton();
        kaderUbahButton = new javax.swing.JButton();
        pasienPanel = new javax.swing.JPanel();
        pasienHapusButton = new javax.swing.JButton();
        pasienUbahButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pasienDataTabel = new javax.swing.JTable();
        pasienTambahButton = new javax.swing.JButton();
        pemeriksaanPanel = new javax.swing.JScrollPane();
        pemeriksaanSubPanel = new javax.swing.JPanel();
        pasienTambahButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        pasienHapusButton3 = new javax.swing.JButton();
        pasienUbahButton3 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        pasienDataTabel3 = new javax.swing.JTable();
        kmsLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        imunisasiLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        pemeriksaanCmbox = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        pasienDataTabel4 = new javax.swing.JTable();
        pasienTambahButton4 = new javax.swing.JButton();
        pasienHapusButton4 = new javax.swing.JButton();
        pasienUbahButton4 = new javax.swing.JButton();
        jadwalLabel = new javax.swing.JLabel();

        pasienTambahButton2.setText("tambah");

        pasienHapusButton2.setText("hapus");

        pasienUbahButton2.setText("ubah");

        pasienDataTabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pasienDataTabel2.setPreferredSize(new java.awt.Dimension(300, 60));
        jScrollPane6.setViewportView(pasienDataTabel2);

        jScrollPane4.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(800, 600));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        splitPanel.setDividerLocation(80);
        splitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setPreferredSize(new java.awt.Dimension(300, 100));

        pencarianButton.setBackground(new java.awt.Color(96, 153, 221));
        pencarianButton.setForeground(new java.awt.Color(255, 255, 255));
        pencarianButton.setText("TEMUKAN");
        pencarianButton.setToolTipText("Pencarian");
        pencarianButton.setPreferredSize(new java.awt.Dimension(100, 30));

        pencarianText.setToolTipText("Kata Kunci Pencarian");
        pencarianText.setPreferredSize(new java.awt.Dimension(200, 30));

        namaAkunLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namaAkunLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaAkunLabel.setText("NAMA");

        pencarianLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pencarianLabel.setForeground(new java.awt.Color(0, 51, 102));
        pencarianLabel.setText("Pencarian");

        subPanel.setBackground(new java.awt.Color(255, 255, 255));
        subPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        kaderPanel.setBackground(new java.awt.Color(255, 255, 255));

        kaderDataTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Lengkap", "Tempat & Tanggal Lahir", "Jenis Kelamin", "Alamat", "Nama Orang Tua"
            }
        ));
        jScrollPane1.setViewportView(kaderDataTabel);

        kaderTambahButton.setText("tambah");

        kaderHapusButton.setText("hapus");

        kaderUbahButton.setText("ubah");

        javax.swing.GroupLayout kaderPanelLayout = new javax.swing.GroupLayout(kaderPanel);
        kaderPanel.setLayout(kaderPanelLayout);
        kaderPanelLayout.setHorizontalGroup(
            kaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kaderTambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kaderHapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kaderUbahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kaderPanelLayout.setVerticalGroup(
            kaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kaderPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(kaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaderTambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kaderHapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kaderUbahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        subPanel.addTab("Kader", kaderPanel);

        pasienPanel.setBackground(new java.awt.Color(255, 255, 255));

        pasienHapusButton.setText("hapus");

        pasienUbahButton.setText("ubah");

        pasienDataTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID PASIEN", "Nama Lengkap", "Tempat & Tanggal Lahir", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(pasienDataTabel);

        pasienTambahButton.setText("tambah");

        javax.swing.GroupLayout pasienPanelLayout = new javax.swing.GroupLayout(pasienPanel);
        pasienPanel.setLayout(pasienPanelLayout);
        pasienPanelLayout.setHorizontalGroup(
            pasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pasienPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pasienTambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasienHapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasienUbahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pasienPanelLayout.setVerticalGroup(
            pasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasienTambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasienHapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasienUbahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        subPanel.addTab("Pasien", pasienPanel);

        pemeriksaanPanel.setBackground(new java.awt.Color(255, 255, 255));

        pemeriksaanSubPanel.setBackground(new java.awt.Color(255, 255, 255));

        pasienTambahButton3.setText("tambah");

        pasienHapusButton3.setText("hapus");

        pasienUbahButton3.setText("ubah");

        pasienDataTabel3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Lengkap", "Tempat & Tanggal Lahir", "Jenis Kelamin", "Alamat", "Nama Orang Tua"
            }
        ));
        pasienDataTabel3.setPreferredSize(new java.awt.Dimension(300, 60));
        jScrollPane8.setViewportView(pasienDataTabel3);

        kmsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kmsLabel.setText("KMS (Kartu Menuju Sehat)");

        jLabel2.setText("Nama  :");

        jLabel3.setText("Umur   :");

        jLabel4.setText("Tinggi  :");

        jLabel5.setText("Berat   :");

        imunisasiLabel.setText("Imunisasi");

        jProgressBar1.setValue(75);

        jLabel12.setText("<?>");

        jLabel13.setText("<?>");

        jLabel14.setText("<?>");

        jLabel15.setText("<?>");

        jCheckBox1.setLabel("Hepatitis B");
        jCheckBox1.setPreferredSize(new java.awt.Dimension(100, 15));

        jCheckBox2.setLabel("Heptitis B");
        jCheckBox2.setPreferredSize(new java.awt.Dimension(100, 15));

        jCheckBox3.setText("BCG");
        jCheckBox3.setPreferredSize(new java.awt.Dimension(100, 15));

        jCheckBox4.setText("Vitamin");
        jCheckBox4.setPreferredSize(new java.awt.Dimension(100, 15));

        jCheckBox5.setText("Campak");
        jCheckBox5.setPreferredSize(new java.awt.Dimension(100, 15));

        pemeriksaanCmbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID" }));

        pasienDataTabel4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID ", "Nama Dokter", "Hari", "Tanggal"
            }
        ));
        pasienDataTabel4.setPreferredSize(new java.awt.Dimension(300, 60));
        jScrollPane9.setViewportView(pasienDataTabel4);

        pasienTambahButton4.setText("tambah");

        pasienHapusButton4.setText("hapus");

        pasienUbahButton4.setText("ubah");

        jadwalLabel.setText("Jadwal");

        javax.swing.GroupLayout pemeriksaanSubPanelLayout = new javax.swing.GroupLayout(pemeriksaanSubPanel);
        pemeriksaanSubPanel.setLayout(pemeriksaanSubPanelLayout);
        pemeriksaanSubPanelLayout.setHorizontalGroup(
            pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pemeriksaanSubPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pemeriksaanCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pemeriksaanSubPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator2))
                        .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14))
                                            .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12))
                                            .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13))
                                            .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15))))
                                    .addComponent(kmsLabel))
                                .addGap(221, 221, 221)
                                .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imunisasiLabel)
                                    .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                                .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                                        .addComponent(pasienTambahButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pasienHapusButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pasienUbahButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                                        .addComponent(pasienTambahButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pasienHapusButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pasienUbahButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jadwalLabel))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pemeriksaanSubPanelLayout.setVerticalGroup(
            pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kmsLabel)
                    .addComponent(imunisasiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                        .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addGap(4, 4, 4)
                        .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel15)))
                    .addGroup(pemeriksaanSubPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(pemeriksaanCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadwalLabel)
                .addGap(5, 5, 5)
                .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pasienTambahButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pasienHapusButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pasienUbahButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pasienTambahButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pasienHapusButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pasienUbahButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pemeriksaanSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pemeriksaanPanel.setViewportView(pemeriksaanSubPanel);
        pemeriksaanSubPanel.getAccessibleContext().setAccessibleName("");

        subPanel.addTab("Pemeriksaan", pemeriksaanPanel);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pencarianLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pencarianText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pencarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaAkunLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pencarianLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pencarianText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaAkunLabel))
                .addGap(18, 18, 18)
                .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        subPanel.getAccessibleContext().setAccessibleName("tab");

        splitPanel.setRightComponent(headerPanel);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel imunisasiLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel jadwalLabel;
    private javax.swing.JTable kaderDataTabel;
    private javax.swing.JButton kaderHapusButton;
    private javax.swing.JPanel kaderPanel;
    private javax.swing.JButton kaderTambahButton;
    private javax.swing.JButton kaderUbahButton;
    private javax.swing.JLabel kmsLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaAkunLabel;
    private javax.swing.JTable pasienDataTabel;
    private javax.swing.JTable pasienDataTabel2;
    private javax.swing.JTable pasienDataTabel3;
    private javax.swing.JTable pasienDataTabel4;
    private javax.swing.JButton pasienHapusButton;
    private javax.swing.JButton pasienHapusButton2;
    private javax.swing.JButton pasienHapusButton3;
    private javax.swing.JButton pasienHapusButton4;
    private javax.swing.JPanel pasienPanel;
    private javax.swing.JButton pasienTambahButton;
    private javax.swing.JButton pasienTambahButton2;
    private javax.swing.JButton pasienTambahButton3;
    private javax.swing.JButton pasienTambahButton4;
    private javax.swing.JButton pasienUbahButton;
    private javax.swing.JButton pasienUbahButton2;
    private javax.swing.JButton pasienUbahButton3;
    private javax.swing.JButton pasienUbahButton4;
    private javax.swing.JComboBox<String> pemeriksaanCmbox;
    private javax.swing.JScrollPane pemeriksaanPanel;
    private javax.swing.JPanel pemeriksaanSubPanel;
    private javax.swing.JButton pencarianButton;
    private javax.swing.JLabel pencarianLabel;
    private javax.swing.JTextField pencarianText;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JTabbedPane subPanel;
    // End of variables declaration//GEN-END:variables
}